server:
  port: 8011

spring:
  application:
    name: service-verification-code

eureka:
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1
#    hostname: service-verification-code
#    instance-id: service-verification-code