server:
  port: 9001

eureka:
  instance:
    hostname: api-passenger
    instance-id: api-passenger
  client:
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/
    register-with-eureka: true
    enabled: true
spring:
  application:
    name: api-passenger

feign:
  compression:
    request:
      mime-types:
      - text/xml
      min-request-size: 2048
  #开启feignhystrix
  hystrix:
    enabled: true